
volumes:
    dados:

services:
    db:
      image: postgres:17.4
      volumes:
       # Volume dos dados
       - dados:/var/lib/postgresql/data
       # Scripts
       - ./scripts:/scripts
       - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      environment:
        POSTGRES_USER: $DB_USUARIO
        POSTGRES_PASSWORD: $DB_SENHA
      ports:
        - $DB_PORT:5432
